describe transac;
describe bank;
describe atm_machine;
describe customer;
describe donation;
describe atm_card;


select *from transac;
select *from bank;
select *from atm_machine;
select *from customer;
select *from donation;
select *from atm_card;

--(LAB 02)

ALTER TABLE DONATION 
ADD USER_NAME VARCHAR(25);

ALTER TABLE DONATION
ADD (VAT NUMBER(3),
SERVICE_CHARGE NUMBER(3));

ALTER TABLE DONATION
MODIFY (VAT NUMBER(2),
SERVICE_CHARGE NUMBER(2));

ALTER TABLE DONATION
DROP COLUMN VAT;
ALTER TABLE DONATION
DROP COLUMN SERVICE_CHARGE;
ALTER TABLE DONATION
DROP COLUMN USER_NAME;


ALTER TABLE BANK 
RENAME COLUMN BANK_BRANCH TO BANK_BRANCH_NAME;

ALTER TABLE BANK 
RENAME COLUMN BANK_BRANCH_NAME TO BANK_BRANCH;

--INSERT CARD VALUE TO SEE UPDATE WORK

UPDATE ATM_CARD 
SET EXPIRY= '03-FEB-22'
WHERE CARD_ID = 111144;

DELETE FROM ATM_CARD 
WHERE CARD_ID = 111144;


-------LAB 03------

SELECT ACC_NO,USER_NAME FROM CUSTOMER;

SELECT CARD_ID FROM TRANSAC;
SELECT DISTINCT(CARD_ID) FROM TRANSAC;

--divide transac_amount by 5 where TRANSAC_AMOUNT>=2000;
SELECT (TRANSAC_AMOUNT/5) FROM TRANSAC
WHERE TRANSAC_AMOUNT>=2000;
--USING 'AS'
SELECT (TRANSAC_AMOUNT/5) AS REDUCED_AMOUNT FROM TRANSAC
WHERE TRANSAC_AMOUNT>=2000;

--USING BETWEEN ,AND
SELECT ACC_NO FROM BANK
WHERE USER_BALANCE BETWEEN 200000 AND 500000;

--DIFF OF 'IN'  ABD 'BETWEEN'
SELECT ACC_NO,USER_NAME FROM CUSTOMER
WHERE USER_BALANCE IN (200000,500000);

--order by
SELECT ACC_NO,USER_BALANCE
FROM CUSTOMER
ORDER BY USER_BALANCE;

SELECT ACC_NO,USER_BALANCE
FROM CUSTOMER
ORDER BY ACC_NO DESC;

SELECT ACC_NO,USER_BALANCE
FROM CUSTOMER
ORDER BY USER_BALANCE,ACC_NO desc;

--like %---%
SELECT USER_NAME, ACC_NO
FROM CUSTOMER
where USER_NAME LIKE '%AV%';

--FIND ACC WHICH HAS NAME STARTED WITH A
SELECT USER_NAME, ACC_NO
FROM CUSTOMER
where USER_NAME LIKE 'A%';

--FIND ACC WHICH HAS NAME ENDS WITH E
SELECT USER_NAME, ACC_NO
FROM CUSTOMER
where USER_NAME LIKE '%E';

--FIND ACC WHICH HAS NAME WITH 'A' IN MIDDLE
SELECT USER_NAME, ACC_NO
FROM CUSTOMER
where USER_NAME LIKE '%_A_%';

--NO ROW COZ NO NAME HAS ONA IN ANY MID POS
SELECT USER_NAME, ACC_NO
FROM CUSTOMER
where USER_NAME LIKE '%_ONA_%';

SELECT USER_NAME, ACC_NO
FROM CUSTOMER
where USER_NAME LIKE '%_NAT_%';


-------LAB 04------

SELECT COUNT(*),COUNT(CARD_PIN) FROM CUSTOMER;

SELECT SUM(USER_BALANCE) FROM CUSTOMER;

SELECT COUNT(DISTINCT BANK_ID) FROM CUSTOMER;
SELECT COUNT(BANK_ID) FROM CUSTOMER;


--111122 HAS MULTIPLE(3) DONATION
SELECT CARD_ID , COUNT(DONATE_AMOUNT)
FROM DONATION
GROUP BY CARD_ID;

SELECT CARD_ID , COUNT(DONATE_AMOUNT)
FROM DONATION
GROUP BY CARD_ID
HAVING CARD_ID<200000;

SELECT CARD_ID , COUNT(DONATE_AMOUNT)
FROM DONATION
WHERE CARD_ID<200000
GROUP BY CARD_ID;
